{% set name = "napari-animated-gif-io" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-animated-gif-io-{{ version }}.tar.gz
  sha256: ab9a3af2f74fd0eb63d99a94cade0a11da8f96dc1307161ec1b755bc815ac540

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - imageio
    - napari
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - numpy
    - python >=3.7

test:
  imports:
    - napari_animated_gif_io
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-animated-gif-io
  summary: Save 3D image stacks as animated gifs
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - haesleinhuepf
